### ISSUE TITLE
Add support for jupyter-releaser

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/gateway_provisioners#10]
We should utilize the [Jupyter-releaser](https://github.com/jupyter-server/jupyter_releaser) tooling to produce releases if possible

**Comment by kevin-bates** [comment]
Some of this was added in #47.  Still need to make the project buildable via hatch (probably need a hook/plugin to deal with `make` builds) and token management - to the "jupyter releaser" user (which may require we be in the `jupyter-server` organization).

**Comment by blink1073** [comment]
Also partially supported by #48.   Agreed we should probably move this repo to `jupyter-server` to finish this issue.  :)

**Comment by kevin-bates** [comment]
Thanks Steve.  I'll add this to next week's team meeting agenda, although I'm not sure I'll be able to attend.
