### ISSUE TITLE
Custom Kernel JSON Configuration Variables

### ISSUE THREAD

**Issue by timg512372** [jupyter-server/gateway_provisioners#101]
Hi, I'm trying to create a custom kernel spec JSON file, and I would like the configuration variables to be available inside a custom gateway_provisioner. I'm looking at this [line of documentation](https://gateway-provisioners.readthedocs.io/en/latest/contributors/system-architecture.html#gateway-provisioners-configuration) under System Architecture

> Each kernel.json’s kernel_provisioner stanza can specify an optional config stanza that is converted into a dictionary of name/value pairs and passed as an argument to each kernel provisioner’s constructor relative to the provisioner identified by the provisioner_name entry.

but when I put variables under the config stanza and inspect the arguments passed into the kernel provisioner's constructor, I don't see any of my configuration variables. Do you know where I might be able to find the configuration variables?

kernel.json
```
{
  "argv": [
  ],
  "env": {},
  "display_name": "Python Custom",
  "language": "python",
  "interrupt_mode": "signal",
  "metadata": {
    "debugger": true,
    "kernel_provisioner": {
      "provisioner_name": "custom-provisioner",
      "config": {
        "launch_timeout": 30,
        "test": "test",
        "test2": "test2"
      }
    }
  }
}
```

**Comment by timg512372** [comment]
Hi @kevin-bates,

Thank you for your help! The key value pairs in the config stanza are indeed into the constructor as keyword arguments, and I can see them in `kwargs` in the `__init__()` method. For context, I was trying to derive off of DistributedProvisioner.

**Comment by kevin-bates** [comment]
Right on - glad to hear that.  If you have any time, it would be great to have an update to the docs.  No worries if not.
