### ISSUE TITLE
Fix docs build issue

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/gateway_provisioners#107]
It looks like the docs builds have been breaking due to an issue in the sequence diagram located in [`docs/source/contributors/sequence-diagrams.md`](https://github.com/jupyter-server/gateway_provisioners/blob/main/docs/source/contributors/sequence-diagrams.md).   Here's a capture of the [build failure](https://github.com/jupyter-server/gateway_provisioners/actions/runs/6187008029/job/16795882933) followed by the error text:

`
dot code 'seqdiag {\n   edge_length = 180;\n   span_height = 15;\n   WebApplication  [label = "Web Application"];\n   HostApplication  [label = "Host Application"];\n   KernelManager  [label = "Kernel Manager"];\n   Provisioner;\n   Kernel;\n   ResourceManager  [label = "Resource Manager"];\n\n  === Kernel Launch ===\n\n  WebApplication -> HostApplication [label = "https POST api/kernels "];\n  HostApplication -> KernelManager [label = "start_kernel() "];\n  KernelManager -> Provisioner [label = "launch_process() "];\n\n  Provisioner -> Kernel [label = "launch kernel"];\n  Provisioner -> ResourceManager [label = "confirm startup"];\n  Kernel --> Provisioner [label = "connection info"];\n  ResourceManager --> Provisioner [label = "state & host info"];\n  Provisioner --> KernelManager [label = "complete connection info"];\n  KernelManager -> Kernel [label = "TCP socket requests"];\n  Kernel --> KernelManager [label = "TCP socket handshakes"];\n  KernelManager --> HostApplication [label = "kernel-id"];\n  HostApplication --> WebApplication [label = "api/kernels response"];\n\n  === Websocket Negotiation ===\n\n  WebApplication -> HostApplication [label = "ws GET api/kernels"];\n  HostApplication -> Kernel [label = "kernel_info_request message"];\n  Kernel --> HostApplication [label = "kernel_info_reply message"];\n  HostApplication --> WebApplication [label = "websocket upgrade response"];\n}': 'ImageDraw' object has no attribute 'textsize'
`

We should probably consider moving the built-in mermaid support.

**Comment by blink1073** [comment]
Done in #128
