### ISSUE TITLE
Why is this named `gateway` provisioners?

### ISSUE THREAD

**Issue by echarles** [jupyter-server/gateway_provisioners#96]
Why is this named `gateway` provisioners and not simply `kernel` provisioners. The intent is that it can be used in any jupyter-client solution.

Similarly, reading the doc, I see mention of `Host`, `Server`... which confuses me at some point. A nomenclature introduction would be great, I can try to open a PR if interest.

cc/ @kevin-bates

**Comment by echarles** [comment]
Too bad I missed https://github.com/jupyter-server/gateway_provisioners/issues/36 - Maybe 22 Dec to 3 Jan was a bit sharp timeframe.

I am not bullish to change the current name, but if it has to be done, it should be done asap while this repo is not yet widely known/used. I understand your logic around gateways, but `Kernel provisioners` sounds to me like a perfect name as this is exactly what it is done. e.g. I am experimenting now launching a remote kernel from `jupyter console`.

Would be good to have a subtitle, but I expect that the needed vocabulary is quite broad. As a picture is worth a thousand words, I'd love an architecture diagram where those words/components would be represented. Aside that diagram, a simple table with the definition for each words/components would be welcome.

**Comment by echarles** [comment]
> Kernel Provisioners is too generic and would conflict with the name of the concept. 

Agree.. then `remote_kernel_provisioners` ?  A bit longer, but self descriptive.

**Comment by echarles** [comment]
gateway_provisioners suffer from the same argument I would say.

I am also sure that the code of this repos does not provision gateways, it provision kernels the provisioner is jupyter_client.

**Comment by kevin-bates** [comment]
I understand. I'm open to another name but it can't be generic or too long. 

I believe this can be addressed via the description and keyword tags personally. 

I'm happy to discuss further here and welcome opinions from others as well.

**Comment by echarles** [comment]
Sounds good. It was more a question to understand the logic and start the discussion. If we don't land another agreed name with folks, I am happy to leave it as-is. Let's leave this open for a few weeks before closing.

**Comment by kevin-bates** [comment]
I've gone ahead and added a description along with some topics (tags) to the repository.  I believe that this, coupled with the [README introduction](https://github.com/jupyter-server/gateway_provisioners#gateway-provisioners), and [pypi.org description](https://pypi.org/project/gateway-provisioners/), should be sufficient information but let's see where this discussion leads.

![Screenshot from 2023-06-15 11-37-11](https://github.com/jupyter-server/gateway_provisioners/assets/22599560/62b71650-67dd-4f32-8329-99eb254bc77a)

**Comment by echarles** [comment]
That is helping.

On thing to note is that a name change has impact not only on the pypi package, but also on a lot of code and variable being prefixed with `gp-` or `GP_`.

The sooner we take a decision, the better, so I propose to keep this open until 31 Jul (or something) max.

**Comment by echarles** [comment]
> so I propose to keep this open until 31 Jul (or something) max.

We are over, so I will close this.
